# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, systemSettings, ... }:
{
	imports =
	[
		"${modulesPath}/installer/scan/not-detected.nix"
	];

	boot =
	{
		initrd =
		{
			availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
			kernelModules = [ "dm-snapshot" ];
			luks =
			{
				devices =
				{
					"${systemSettings.fileSystem.encrypted.alias}" =
					{
						device = "/dev/disk/by-label/${systemSettings.fileSystem.encrypted.label}";
					};
				};
			};
		};
		kernelModules = [ "kvm-amd" ];
		extraModulePackages = [ ];
	};

	fileSystems =
	{
		"/" =
		{
			device = "/dev/disk/by-label/${systemSettings.fileSystem.root.label}";
			fsType = systemSettings.fileSystem.root.type;
		};

		"/boot" =
		{
			device = "/dev/disk/by-label/${systemSettings.fileSystem.boot.label}";
			fsType = systemSettings.fileSystem.boot.type;
			options = [ "fmask=0022" "dmask=0022" ];
		};
	};

	swapDevices =
	[
		{
			device = "/dev/disk/by-label/${systemSettings.fileSystem.swap.label}";
		}
	];

	nixpkgs =
	{
		hostPlatform = lib.mkDefault systemSettings.arch;
	};

	hardware =
	{
		cpu =
		{
			amd =
			{
				updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
			};
		};
	};
}
